# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabsWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabsWidget.sizePolicy().hasHeightForWidth())
        self.tabsWidget.setSizePolicy(sizePolicy)
        self.tabsWidget.setObjectName("tabsWidget")
        self.mTab = QtWidgets.QWidget()
        self.mTab.setObjectName("mTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.mFromLabel = QtWidgets.QLabel(self.mTab)
        self.mFromLabel.setObjectName("mFromLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mFromLabel)
        self.mFromDateTimeEdit = QtWidgets.QDateTimeEdit(self.mTab)
        self.mFromDateTimeEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mFromDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.mFromDateTimeEdit.setSizePolicy(sizePolicy)
        self.mFromDateTimeEdit.setObjectName("mFromDateTimeEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mFromDateTimeEdit)
        self.mToLabel = QtWidgets.QLabel(self.mTab)
        self.mToLabel.setObjectName("mToLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mToLabel)
        self.mToDateTimeEdit = QtWidgets.QDateTimeEdit(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mToDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.mToDateTimeEdit.setSizePolicy(sizePolicy)
        self.mToDateTimeEdit.setObjectName("mToDateTimeEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mToDateTimeEdit)
        self.skupinaMEnLabel = QtWidgets.QLabel(self.mTab)
        self.skupinaMEnLabel.setObjectName("skupinaMEnLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.skupinaMEnLabel)
        self.mGroupComboBox = QtWidgets.QComboBox(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mGroupComboBox.sizePolicy().hasHeightForWidth())
        self.mGroupComboBox.setSizePolicy(sizePolicy)
        self.mGroupComboBox.setObjectName("mGroupComboBox")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mGroupComboBox)
        self.mDeviceLabel = QtWidgets.QLabel(self.mTab)
        self.mDeviceLabel.setObjectName("mDeviceLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mDeviceLabel)
        self.mDeviceComboBox = QtWidgets.QComboBox(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mDeviceComboBox.sizePolicy().hasHeightForWidth())
        self.mDeviceComboBox.setSizePolicy(sizePolicy)
        self.mDeviceComboBox.setObjectName("mDeviceComboBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mDeviceComboBox)
        self.mUnitLabel = QtWidgets.QLabel(self.mTab)
        self.mUnitLabel.setObjectName("mUnitLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mUnitLabel)
        self.mUnitComboBox = QtWidgets.QComboBox(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mUnitComboBox.sizePolicy().hasHeightForWidth())
        self.mUnitComboBox.setSizePolicy(sizePolicy)
        self.mUnitComboBox.setObjectName("mUnitComboBox")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mUnitComboBox)
        self.mDeviatedLabel = QtWidgets.QLabel(self.mTab)
        self.mDeviatedLabel.setObjectName("mDeviatedLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.mDeviatedLabel)
        self.mDeviatedCheckBox = QtWidgets.QCheckBox(self.mTab)
        self.mDeviatedCheckBox.setText("")
        self.mDeviatedCheckBox.setObjectName("mDeviatedCheckBox")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.mDeviatedCheckBox)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.mXLabel = QtWidgets.QLabel(self.mTab)
        self.mXLabel.setObjectName("mXLabel")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mXLabel)
        self.mXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mXDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.mXDoubleSpinBox.setSizePolicy(sizePolicy)
        self.mXDoubleSpinBox.setObjectName("mXDoubleSpinBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mXDoubleSpinBox)
        self.mYLabel = QtWidgets.QLabel(self.mTab)
        self.mYLabel.setObjectName("mYLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mYLabel)
        self.mYDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mYDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.mYDoubleSpinBox.setSizePolicy(sizePolicy)
        self.mYDoubleSpinBox.setObjectName("mYDoubleSpinBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mYDoubleSpinBox)
        self.mToleranceLabel = QtWidgets.QLabel(self.mTab)
        self.mToleranceLabel.setObjectName("mToleranceLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.mToleranceLabel)
        self.mToleranceDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mToleranceDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.mToleranceDoubleSpinBox.setSizePolicy(sizePolicy)
        self.mToleranceDoubleSpinBox.setObjectName("mToleranceDoubleSpinBox")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.mToleranceDoubleSpinBox)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.mCancelFilterPushButton = QtWidgets.QPushButton(self.mTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mCancelFilterPushButton.sizePolicy().hasHeightForWidth())
        self.mCancelFilterPushButton.setSizePolicy(sizePolicy)
        self.mCancelFilterPushButton.setObjectName("mCancelFilterPushButton")
        self.verticalLayout_2.addWidget(self.mCancelFilterPushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mTableView = QtWidgets.QTableView(self.mTab)
        self.mTableView.setObjectName("mTableView")
        self.verticalLayout.addWidget(self.mTableView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.mPaginationStartPushButton = QtWidgets.QPushButton(self.mTab)
        self.mPaginationStartPushButton.setObjectName("mPaginationStartPushButton")
        self.horizontalLayout_3.addWidget(self.mPaginationStartPushButton)
        self.mPaginationPreviousPushButton = QtWidgets.QPushButton(self.mTab)
        self.mPaginationPreviousPushButton.setObjectName("mPaginationPreviousPushButton")
        self.horizontalLayout_3.addWidget(self.mPaginationPreviousPushButton)
        self.mPaginationSpinBox = QtWidgets.QSpinBox(self.mTab)
        self.mPaginationSpinBox.setObjectName("mPaginationSpinBox")
        self.horizontalLayout_3.addWidget(self.mPaginationSpinBox)
        self.mPaginationNextPushButton = QtWidgets.QPushButton(self.mTab)
        self.mPaginationNextPushButton.setObjectName("mPaginationNextPushButton")
        self.horizontalLayout_3.addWidget(self.mPaginationNextPushButton)
        self.mPaginationEndPushButton = QtWidgets.QPushButton(self.mTab)
        self.mPaginationEndPushButton.setObjectName("mPaginationEndPushButton")
        self.horizontalLayout_3.addWidget(self.mPaginationEndPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.tabsWidget.addTab(self.mTab, "")
        self.gTab = QtWidgets.QWidget()
        self.gTab.setObjectName("gTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.gTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gTableView = QtWidgets.QTableView(self.gTab)
        self.gTableView.setObjectName("gTableView")
        self.verticalLayout_5.addWidget(self.gTableView)
        self.gRemoveRowPushButton = QtWidgets.QPushButton(self.gTab)
        self.gRemoveRowPushButton.setObjectName("gRemoveRowPushButton")
        self.verticalLayout_5.addWidget(self.gRemoveRowPushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabsWidget.addTab(self.gTab, "")
        self.dTab = QtWidgets.QWidget()
        self.dTab.setObjectName("dTab")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.dTab)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dTableView = QtWidgets.QTableView(self.dTab)
        self.dTableView.setObjectName("dTableView")
        self.verticalLayout_6.addWidget(self.dTableView)
        self.dRemoveRowPushButton = QtWidgets.QPushButton(self.dTab)
        self.dRemoveRowPushButton.setObjectName("dRemoveRowPushButton")
        self.verticalLayout_6.addWidget(self.dRemoveRowPushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.tabsWidget.addTab(self.dTab, "")
        self.lTab = QtWidgets.QWidget()
        self.lTab.setObjectName("lTab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.lTab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lFromLabel = QtWidgets.QLabel(self.lTab)
        self.lFromLabel.setObjectName("lFromLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lFromLabel)
        self.lFromDateTimeEdit = QtWidgets.QDateTimeEdit(self.lTab)
        self.lFromDateTimeEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lFromDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.lFromDateTimeEdit.setSizePolicy(sizePolicy)
        self.lFromDateTimeEdit.setObjectName("lFromDateTimeEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lFromDateTimeEdit)
        self.lToLabel = QtWidgets.QLabel(self.lTab)
        self.lToLabel.setObjectName("lToLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lToLabel)
        self.lToDateTimeEdit = QtWidgets.QDateTimeEdit(self.lTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lToDateTimeEdit.sizePolicy().hasHeightForWidth())
        self.lToDateTimeEdit.setSizePolicy(sizePolicy)
        self.lToDateTimeEdit.setObjectName("lToDateTimeEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lToDateTimeEdit)
        self.verticalLayout_7.addLayout(self.formLayout_3)
        self.lTableView = QtWidgets.QTableView(self.lTab)
        self.lTableView.setObjectName("lTableView")
        self.verticalLayout_7.addWidget(self.lTableView)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.lPaginationStartPushButton = QtWidgets.QPushButton(self.lTab)
        self.lPaginationStartPushButton.setObjectName("lPaginationStartPushButton")
        self.horizontalLayout_8.addWidget(self.lPaginationStartPushButton)
        self.lPaginationPreviousPushButton = QtWidgets.QPushButton(self.lTab)
        self.lPaginationPreviousPushButton.setObjectName("lPaginationPreviousPushButton")
        self.horizontalLayout_8.addWidget(self.lPaginationPreviousPushButton)
        self.lPaginationSpinBox = QtWidgets.QSpinBox(self.lTab)
        self.lPaginationSpinBox.setObjectName("lPaginationSpinBox")
        self.horizontalLayout_8.addWidget(self.lPaginationSpinBox)
        self.lPaginationNextPushButton = QtWidgets.QPushButton(self.lTab)
        self.lPaginationNextPushButton.setObjectName("lPaginationNextPushButton")
        self.horizontalLayout_8.addWidget(self.lPaginationNextPushButton)
        self.lPaginationEndPushButton = QtWidgets.QPushButton(self.lTab)
        self.lPaginationEndPushButton.setObjectName("lPaginationEndPushButton")
        self.horizontalLayout_8.addWidget(self.lPaginationEndPushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.tabsWidget.addTab(self.lTab, "")
        self.horizontalLayout_2.addWidget(self.tabsWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menuBar.setObjectName("menuBar")
        self.menu_Soubor = QtWidgets.QMenu(self.menuBar)
        self.menu_Soubor.setObjectName("menu_Soubor")
        self.menuO_aplikaci = QtWidgets.QMenu(self.menuBar)
        self.menuO_aplikaci.setObjectName("menuO_aplikaci")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Import = QtWidgets.QAction(MainWindow)
        self.action_Import.setObjectName("action_Import")
        self.action_Export = QtWidgets.QAction(MainWindow)
        self.action_Export.setObjectName("action_Export")
        self.menu_Soubor.addAction(self.action_Import)
        self.menu_Soubor.addAction(self.action_Export)
        self.menuBar.addAction(self.menu_Soubor.menuAction())
        self.menuBar.addAction(self.menuO_aplikaci.menuAction())

        self.retranslateUi(MainWindow)
        self.tabsWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mFromLabel.setText(_translate("MainWindow", "Od"))
        self.mToLabel.setText(_translate("MainWindow", "Do"))
        self.skupinaMEnLabel.setText(_translate("MainWindow", "Skupina měření"))
        self.mDeviceLabel.setText(_translate("MainWindow", "Přístroj"))
        self.mUnitLabel.setText(_translate("MainWindow", "Veličina"))
        self.mDeviatedLabel.setText(_translate("MainWindow", "Mimo odchylku"))
        self.mXLabel.setText(_translate("MainWindow", "X"))
        self.mYLabel.setText(_translate("MainWindow", "Y"))
        self.mToleranceLabel.setText(_translate("MainWindow", "Tolerance"))
        self.mCancelFilterPushButton.setText(_translate("MainWindow", "Zrušit filtrování"))
        self.mPaginationStartPushButton.setText(_translate("MainWindow", "<<"))
        self.mPaginationPreviousPushButton.setText(_translate("MainWindow", "<"))
        self.mPaginationNextPushButton.setText(_translate("MainWindow", ">"))
        self.mPaginationEndPushButton.setText(_translate("MainWindow", ">>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.mTab), _translate("MainWindow", "Měření"))
        self.gRemoveRowPushButton.setText(_translate("MainWindow", "Odstranit řádek"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.gTab), _translate("MainWindow", "Skupiny měření"))
        self.dRemoveRowPushButton.setText(_translate("MainWindow", "Odstranit řádek"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.dTab), _translate("MainWindow", "Přístroje"))
        self.lFromLabel.setText(_translate("MainWindow", "Od"))
        self.lToLabel.setText(_translate("MainWindow", "Do"))
        self.lPaginationStartPushButton.setText(_translate("MainWindow", "<<"))
        self.lPaginationPreviousPushButton.setText(_translate("MainWindow", "<"))
        self.lPaginationNextPushButton.setText(_translate("MainWindow", ">"))
        self.lPaginationEndPushButton.setText(_translate("MainWindow", ">>"))
        self.tabsWidget.setTabText(self.tabsWidget.indexOf(self.lTab), _translate("MainWindow", "Log"))
        self.menu_Soubor.setTitle(_translate("MainWindow", "&Soubor"))
        self.menuO_aplikaci.setTitle(_translate("MainWindow", "O aplikaci"))
        self.action_Import.setText(_translate("MainWindow", "&Import"))
        self.action_Export.setText(_translate("MainWindow", "&Export"))

